# Generated by Django 4.2.5 on 2023-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='image',
            field=models.ImageField(null=True, upload_to='portfolio/images/'),
        ),
    ]
