# Generated by Django 4.2.5 on 2023-10-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='subtitle',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
