# Generated by Django 4.2.5 on 2023-12-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_timeline_subtitle_alter_timeline_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='end_date',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='start_date',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
