# Generated by Django 5.0 on 2023-12-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_timeline_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skill1',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skill2',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skill3',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skill4',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
