# Generated by Django 5.0.7 on 2024-08-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_project_skill1_alter_project_skill2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timeline',
            new_name='Experience',
        ),
    ]
