# Generated by Django 5.0.7 on 2024-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_rename_timeline_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='image_small',
            field=models.ImageField(null=True, upload_to='portfolio/images/'),
        ),
    ]
