# Generated by Django 5.0.7 on 2025-05-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_experience_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='tags',
        ),
    ]
