# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_experience_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonCardCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_id", models.CharField(max_length=40, unique=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("image_small", models.URLField(blank=True)),
                ("image_large", models.URLField(blank=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pokemon card cache",
                "verbose_name_plural": "Pokemon card cache",
                "ordering": ["card_id"],
            },
        ),
        migrations.CreateModel(
            name="Slab",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_id", models.CharField(max_length=40)),
                ("grader", models.CharField(max_length=20)),
                ("grade", models.CharField(max_length=10)),
                ("certification_number", models.CharField(blank=True, max_length=60)),
                ("slab_photo", models.ImageField(blank=True, upload_to="portfolio/slabs/")),
                ("featured", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BinderSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_id", models.CharField(max_length=40, unique=True)),
                ("owned", models.BooleanField(default=False)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=140)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
