# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_pokemoncardcache_slab_binderslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="binderslot",
            name="internal_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="slab",
            name="internal_name",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
