# Generated by Codex on 2026-07-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_binderslot_internal_name_slab_internal_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BinderSlot",
        ),
    ]
