# Generated by Codex on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_delete_binderslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyAlbumPick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("spotify_album_id", models.CharField(max_length=80, unique=True)),
                ("title", models.CharField(blank=True, max_length=180)),
                ("artist", models.CharField(blank=True, max_length=180)),
                ("cover_image_url", models.URLField(blank=True)),
                ("spotify_url", models.URLField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("featured", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
