# Generated by Codex on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_spotifyalbumpick"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyalbumpick",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
