export const TEAM_MAP: Record<string, string> = {
  "FNATIC": "FNC",
  "Team Heretics": "TH",
  "GIANTX": "GX",
  "Team Liquid": "TL",
  "Natus Vincere": "NAVI",
  "BBL Esports": "BBL",
  "Karmine Corp": "KC",
  "Team Vitality": "VIT",
  "PCIFIC Esports": "PCF",
  "ULF Esports": "ULF",
  "Gentle Mates": "M8",
  "FUT Esports": "FUT",
  "Wolves Esports": "WOL",
  "Paper Rex": "PRX",
  "Rex Regum Qeon": "RRQ",
  "Gen.G": "GEN",
  "T1": "T1",
  "Sentinels": "SEN",
  "G2 Esports": "G2",
  "NRG": "NRG",
  "LOUD": "LOUD",
  "MIBR": "MIBR",
  "100 Thieves": "100T",
  "Evil Geniuses": "EG",
  "Cloud9": "C9",
  "FURIA": "FUR",
  "KRÜ Esports": "KRÜ",
  "LEVIATÁN": "LEV",
  "ENVY": "ENVY",
  "DetonatioN FocusMe": "DFM",
  "DRX": "DRX",
  "Global Esports": "GE",
  "Team Secret": "TS",
  "ZETA DIVISION": "ZETA",
  "FULL SENSE": "FS",
  "Nongshim RedForce": "NS",
  "VARREL": "VL",
  "All Gamers": "AG",
  "Bilibili Gaming": "BLG",
  "EDward Gaming": "EDG",
  "FunPlus Phoenix": "FPX",
  "JD Gaming": "JDG",
  "Nova Esports": "NOVA",
  "Titan Esports Club": "TEC",
  "Trace Esports": "TE",
  "TYLOO": "TYL",
  "Dragon Ranger Gaming": "DRG",
  "Xi Lai Gaming": "XLG",
};
